version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blogql-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - blogql-network
    env_file:
      - .env

networks:
  blogql-network: